# https://numtide.github.io/devshell
# https://numtide.github.io/devshell/getting_started.html
[[commands]]
package = "hello"

[[env]]
name = "GO111MODULE"
value = "on"

[devshell]
packages = ["minikube", "nodejs", "cowsay"]

[[commands]]
name = "someSpecialCommand"
help = "does something amazing"
command = """\
  cowsay moo
  """

[[commands]]
name = "cluster:dashboard"
category = "cluster commands"
help = "A web based dashboard to view the minikube cluster"
command = """\
minikube dashboard
"""

[[commands]]
name = "cluster:start"
category = "cluster commands"
help = "starts a local minikube cluster"
command = """\
minikube start
minikube addons enable ingress
"""

[[commands]]
name = "cluster:reset"
category = "cluster commands"
help = "completely reset the local cluster (start fresh)"
command = """\
minikube stop
minikube delete
minikube start
"""
