# https://numtide.github.io/devshell
# https://numtide.github.io/devshell/getting_started.html
[[commands]]
package = "hello"

[[commands]]
package = "nodejs"

[[commands]]
package = "minikube"

[[env]]
name = "GO111MODULE"
value = "on"

[devshell]
packages = ["minikube", "nodejs", "cowsay"]

[[commands]]
name = "someSpecialCommand"
help = "does something amazing"
command = """\
  cowsay moo
  """

[serviceGroups.minikube]
description = "Starts minikube cluster"
[serviceGroups.database.services.postgres]
command = "minikube start"
