# https://numtide.github.io/devshell
# https://numtide.github.io/devshell/getting_started.html
[[commands]]
package = "hello"

[[commands]]
package = "nodejs"

[[commands]]
package = "minikube"

[[env]]
name = "GO111MODULE"
value = "on"

[devshell]
packages = ["minikube", "nodejs", "cowsay"]

[[commands]]
name = "someSpecialCommand"
help = "does something amazing"
command = """\
  cowsay moo
  """

[serviceGroups.cluster]
description = "ZStarts Yminikube BclusterA"
[serviceGroups.cluster.services.minikube.start]
command = "minikube start"
[serviceGroups.cluster.services.minikube.stop]
command = "minikube stop"
