# https://numtide.github.io/devshell
# https://numtide.github.io/devshell/getting_started.html
[[commands]]
package = "hello"

[[commands]]
package = "nodejs_20"

[[env]]
name = "GO111MODULE"
value = "on"

[devshell]
packages = ["minikube", "nodejs", "cowsay"]

[[commands]]
name = "someSpecialCommand"
help = "does something amazing"
command = """\
  cowsay moo
  """

[serviceGroups.database]
description = "Runs a database in the background"
[serviceGroups.database.services.postgres]
command = "postgres -D ./pgdata"
[serviceGroups.database.services.memcached]
command = "memcached"
